### ISSUE TITLE
Broken link on FYP Report

### ISSUE THREAD

**Issue by x-ji** [eric-haibin-lin/eric-haibin-lin.github.io#1]
The link on FYP report on the sdb webpage is broken. It should be http://www.linhaibin.com/sdb/files/FYP%20Report.pdf with a uppercase R. Currently it's http://www.linhaibin.com/sdb/files/FYP%20report.pdf which is lowercase and results in a file not found error :)

**Comment by eric-haibin-lin** [comment]
Thanks. Fixed.
